### ISSUE TITLE
An option to control relative positioning

### ISSUE THREAD

**Issue by itsrachelfish** [wetfish/dragondrop#3]
There should be an option to control relative positioning (percent based) vs absolute (pixel based). 

Like this!

``` js
$('.element').dragondrop({position: 'percent'});
$('.element').dragondrop({position: 'pixel'});
```

Or this?

``` js
$('.element').dragondrop({position: '%'});
$('.element').dragondrop({position: 'px'});
```

**Comment by pielover88888** [comment]
The second one, because CSS-style.

**Comment by itsrachelfish** [comment]
This is fixed now, decided to use the shorter "%" / "px" style.

At the moment the only options are percent and px, but it might be nice to support other units of measurement in the future. ems?

**Comment by itsrachelfish** [comment]
As of v0.5 this option has been renamed to "units" as in units of measurement.
